### ISSUE TITLE
Document DB Design

### ISSUE THREAD

**Issue by raffikrikorian** [raffikrikorian/tee_time_sniper#3]

**Comment by HragY** [comment]
3 collections: "courses", "endpoints", "requests"
Endpoints and Courses will be manually inserted in different collections. The documentId of the courses collections will be the course-name or id used in the request. Each course will contain the documentId of the endpoint. The endpoints will contain the request and response parameter(field names).
A user will insert a request in the collection:
We also need to store the user info in a collection in order to identify if a user is premium or not. 

Collection name: 'request' documentId is AI
- completed - boolean to identify if the request is finished.
- coursesArray - Array of String contains the id of the courses requested to sniper
- dateMiliseconds - number - the day for which to sniper epoch value.
- startTime - String - the day start time in 24 hour format 
- endTime - String - the day end time in 24 hour format 
- numberOfPlayers - number
- email - String - optional for free users.
- phone - String - optional for premium users.
- createTimestamp - timestamp

Collection name: 'endpoints' documentId is AI will server as endpointId
- dataRequest - String containing the request body with the values "$courses", "$date", "$startTime", "$endTime", "$numberOfPlayers" in the correct locations to be replaced by the batch job.
- dateFormatPattern - String - The format to be used in the "$date" field example:"MM/DD/YYYY"
- hostnameUrl - String - the URL to send the request to.
- responseValueField - String - the parent value to get the result fields.
- responseAmountField - String - the field containing the amount
- responseCourseNameField - String - the field containing the name of the course
- responseCurrencyField  - String - Optional the field containing the currency of the amount.
- responseTimeField - String - the field containing the time.
- searchpath - String the link to return to the user for them to be able to reserve the spot

Collection name: 'courses' documentId is the courseId to be used in the search
- name - String - detailed name of the course.
- endpoint - String - endpointId containing the info of the request.

Collection name: 'users' documentId will be the firebase UID
- email - String - optional
- phone - String - optional
- createTimestamp - timestamp
- premium - boolean
